name: Feature request
description: Suggest an improvement
title: "[feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: "I can't extract KAY archive payloads when..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: "Add a flag to force checksum/no-checksum mode..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false
